version: '3'
services:
  sigortakontrol:
    image: sigortakontrol:v1
    ports:
      - "6080:80"
      - "6443:443"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sigortakontrol.entrypoints=http"
      - "traefik.http.routers.sigortakontrol.rule=Host(`www.sigortakontrol.com`)"
      - "traefik.http.middlewares.sigortakontrol-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.sigortakontrol.middlewares=sigortakontrol-https-redirect"
      - "traefik.http.routers.sigortakontrol-secure.entrypoints=https"
      - "traefik.http.routers.sigortakontrol-secure.rule=Host(`www.sigortakontrol.com`)"
      - "traefik.http.routers.sigortakontrol-secure.tls=true"
      - "traefik.http.routers.sigortakontrol-secure.tls.certresolver=http"
      - "traefik.http.routers.sigortakontrol-secure.service=sigortakontrol"
      - "traefik.http.services.sigortakontrol.loadbalancer.server.port=6443"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true