version: '3'
services:
  sigortakontrol:
    image: sigortakontrol:v1
    ports:
      - "6000:80"
    networks:
      - proxy
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.sigortakontrol.rule=Host(`www.sigortakontrol.com`,`sigortakontrol.com`)"
      - "traefik.http.routers.sigortakontrol.entrypoints=https"
      - "traefik.http.routers.sigortakontrol.tls.certresolver=http"

networks:
  proxy:
    external: true