version: '3'
services:
  sigortakontrol:
    image: sigortakontrol:v1
    ports:
      - "6000:80"
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.sigortakontrol.rule=Host(`www.sigortakontrol.com`,`sigortakontrol.com`)"
      - "traefik.http.routers.sigortakontrol.entrypoints=https"
      - "traefik.http.routers.sigortakontrol.tls.certresolver=http"
      - "traefik.http.middlewares.sigortakontrol-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.sigortakontrol.middlewares=sigortakontrol-https-redirect"
      - "traefik.http.routers.sigortakontrol-secure.entrypoints=https"
      - "traefik.http.routers.sigortakontrol-secure.rule=Host(`www.sigortakontrol.com`,`sigortakontrol.com`)"
      - "traefik.http.routers.sigortakontrol-secure.tls=true"
      - "traefik.http.routers.sigortakontrol-secure.tls.certresolver=http"
      - "traefik.http.routers.sigortakontrol-secure.service=sigortakontrol"

networks:
  proxy:
    external: true