version: '3'
services:
  sitekontrol:
    image: sigortakontrol:v1
    ports:
      - "6000:80"
    networks:
      - proxy
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.sitekontrol.rule=Host(`www.sigortakontrol.com`)"
      - "traefik.http.routers.sitekontrol.entrypoints=https"
      - "traefik.http.routers.sitekontrol.tls.certresolver=http"

networks:
  proxy:
    external: true